language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: IZRJRECcBgsL3DCs/c3LbAbK/RM2DIZBEmHSKigA0HYaJQv7e+I7Oi9ma0xAvQPZMMa/aqAd4pZCMBV5PRzOSsx8QB3omErHMfaet7SCOOpMzrSZ085RgDGYqZihhgKPQ/WhIKqp/+xFKgplV4Q1Ut2I1MqNDR5qCuHiIH6cqYKD49C4ZgYqAsyFrLOB3cqXw+delnC6NSnLUmgrrugzmHswtWxqU3xmnZ9tq+NQSSxaUJdPDs9Z5s6fTJomwKEhGzjKf4OisXhc9hJVekey9u6cZhjWwVAfuWEVWNbssi2m81BW8kkzX4OgdKPlhFVFJdmyubvPU0eB4vdTBqmuiABQWDxRvxrMVm/vAX7WUGhCDDVsuGk7xVVoTf0nxGdZijK6OhaqJh3R0WVifCS04JzV4VIK8W7TLDYZkE6DuDNlABvYpV2yGs6I4rfRRNPVYW24SBru6UkoGNqjsKwZDTaYvd4xFBW5bSMgNMMAcRVpBJ863/6sZLiYukZcDoQHhmDTHu6hChF+0mngJ03zzwSSgVlwqBVwLHXPSJ8VI1F42xEv3fl+QjDxuq5xQdBONF3I7eG3Y/z8H7aemRUxJiZ/NwQGHi0435icFK4oeQ3bnL6hKeEO+oKYz+pnj/aW/9P0HcMcdmsjuLjk2RbY6CMyIn0zYUNaQjTtW9Ny7I0=
